apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hockey.fullname" . }}-redis
  labels:
    app: {{ include "hockey.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hockey.name" . }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ include "hockey.name" . }}
        component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379
          resources: {}
